<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $documentTitle }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #334155; font-size: 13px; margin: 0; padding: 36px; }
        h1 { color: #0f172a; font-size: 22px; margin: 0 0 8px; }
        .meta { color: #64748b; margin-bottom: 28px; }
        .box { border: 2px solid #0f172a; padding: 22px; border-radius: 6px; margin-top: 24px; }
        .label { font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: bold; margin-bottom: 4px; }
        .footer { margin-top: 40px; font-size: 11px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    </style>
</head>
<body>
    @if($user->logoDataUriForPdf())
        <img src="{{ $user->logoDataUriForPdf() }}" style="max-height: 60px; max-width: 180px; margin-bottom: 16px;">
    @endif
    <h1>{{ $documentTitle }}</h1>
    <div class="meta">Professional stamp sheet · {{ \Illuminate\Support\Carbon::parse($stampDate)->format('d M Y') }}</div>

    <div class="box">
        <div class="label">Practitioner</div>
        <div style="font-size: 16px; font-weight: bold; color: #0f172a; margin-bottom: 12px;">{{ $user->name }}</div>
        @if($user->postnominalsLine())
            <div style="margin-bottom: 12px; color: #64748b;">{{ $user->postnominalsLine() }}</div>
        @endif
        <div class="label">Profession</div>
        <div style="margin-bottom: 12px;">{{ $user->profession }}</div>
        @if($user->warrant_type || $user->warrant_number)
            <div class="label">Warrant</div>
            <div style="margin-bottom: 12px;">{{ trim(($user->warrant_type ?? '') . ' ' . ($user->warrant_number ?? '')) }}</div>
        @endif
        @if($projectReference)
            <div class="label">Project reference</div>
            <div style="margin-bottom: 12px;">{{ $projectReference }}</div>
        @endif
        <div class="label">Declaration</div>
        <div style="line-height: 1.5;">{{ $declaration }}</div>
    </div>

    <div class="footer">
        Generated by PractisBase Document Stamper. This sheet is a professional declaration aid, not a government-certified stamp.
    </div>
</body>
</html>
