<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $documentTitle }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #334155; font-size: 13px; margin: 0; padding: 36px; }
        h1 { color: #0f172a; font-size: 22px; margin: 0 0 8px; }
        .meta { color: #64748b; margin-bottom: 24px; }
        .box { border: 2px solid #0f172a; padding: 22px; border-radius: 6px; margin-top: 18px; }
        .label { font-size: 11px; text-transform: uppercase; color: #64748b; font-weight: bold; margin-bottom: 4px; }
        .body-text { line-height: 1.55; white-space: pre-wrap; }
        .footer { margin-top: 40px; font-size: 10px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 12px; }
        .stamp { margin-top: 28px; border-top: 1px dashed #cbd5e1; padding-top: 16px; }
    </style>
</head>
<body>
    @if($user->logoDataUri())
        <img src="{{ $user->logoDataUri() }}" style="max-height: 60px; max-width: 180px; margin-bottom: 16px;">
    @endif
    <h1>{{ $documentTitle }}</h1>
    <div class="meta">
        {{ $entry->entry_date->format('d M Y') }}
        · Patient ref {{ $patient->public_ref }}
    </div>

    <div class="box">
        <div class="label">Patient</div>
        <div style="font-size: 16px; font-weight: bold; color: #0f172a; margin-bottom: 12px;">
            {{ $patientPayload['display_name'] ?? 'Patient' }}
        </div>
        @if(!empty($patientPayload['date_of_birth']))
            <div class="label">Date of birth</div>
            <div style="margin-bottom: 12px;">{{ \Illuminate\Support\Carbon::parse($patientPayload['date_of_birth'])->format('d M Y') }}</div>
        @endif

        <div class="label">{{ match($entry->entry_type) {
            'prescription' => 'Prescription',
            'referral' => 'Referral',
            'certificate' => 'Certificate',
            default => 'Document',
        } }} title</div>
        <div style="font-weight: bold; margin-bottom: 12px;">{{ $entryPayload['title'] ?? '' }}</div>

        <div class="label">Details</div>
        <div class="body-text">{{ $entryPayload['body'] ?? '' }}</div>
    </div>

    <div class="stamp">
        <div class="label">Issued / stamped by</div>
        <div style="font-size: 15px; font-weight: bold; color: #0f172a;">{{ $user->name }}</div>
        <div>{{ $user->profession }}</div>
        @if($user->warrant_type || $user->warrant_number)
            <div>Warrant: {{ trim(($user->warrant_type ?? '') . ' ' . ($user->warrant_number ?? '')) }}</div>
        @endif
        @if($user->vat_number)
            <div>VAT: {{ $user->vat_number }}</div>
        @endif
    </div>

    <div class="footer">
        Generated by PractisBase after vault unlock. This document is a professional aid — not a government-certified form and not a substitute for your clinical duty of care.
        Paid one-time patient delivery links are a later roadmap phase.
    </div>
</body>
</html>
