<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>TA22 Summary {{ $selectedYear }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #334155; font-size: 13px; margin: 0; padding: 28px; }
        h1 { color: #0f172a; font-size: 22px; margin: 0 0 6px; }
        .muted { color: #64748b; margin-bottom: 22px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }
        th { background: #f8fafc; width: 45%; }
        .note { margin-top: 28px; font-size: 11px; color: #64748b; line-height: 1.5; border-top: 1px solid #e2e8f0; padding-top: 14px; }
    </style>
</head>
<body>
    <h1>TA22 Part-Time Scheme Summary</h1>
    <div class="muted">{{ $user->name }} · Fiscal year {{ $selectedYear }} · Generated by PractisBase</div>

    <table>
        <tr><th>Official invoiced revenue</th><td>€{{ number_format($invoicedRevenue, 2) }}</td></tr>
        <tr><th>Deductible expenses ({{ $expenseInfo['source'] === 'ledger' ? 'expense ledger' : 'Settings estimate' }})</th><td>€{{ number_format($deductibleExpenses, 2) }}</td></tr>
        <tr><th>Net business profit</th><td>€{{ number_format($netProfit, 2) }}</td></tr>
        <tr><th>TA22 annual cap</th><td>€{{ number_format($ta22Cap, 2) }}</td></tr>
        <tr><th>Amount eligible for TA22</th><td>€{{ number_format($amountEligibleForTa22, 2) }}</td></tr>
        <tr><th>TA22 flat rate</th><td>{{ number_format($ta22Rate * 100, 2) }}%</td></tr>
        <tr><th>TA22 tax due</th><td><strong>€{{ number_format($ta22Liability, 2) }}</strong></td></tr>
        <tr><th>Spillover into progressive brackets</th><td>€{{ number_format($spilloverProfit, 2) }}</td></tr>
    </table>

    <div class="note">
        This summary is generated from PractisBase ledger data for your records and accountant. It is not a certified government form and does not replace official CFR filings.
        Password reset / login credentials never unlock medical vaults. PractisBase is a tool, not certified accounting software.
    </div>
</body>
</html>
